### ISSUE TITLE
Moving records not working in the RideSheet Public Sample v1

### ISSUE THREAD

**Issue by keviniano** [full-path/ridesheet#64]
One trip appears to move, but then the process is halted. Two possible issues here:

- A bug that needs fixing
- There's a user-solvable problem in the spreadsheet, but there's not enough explanation in the message the user gets to know how to fix.

**Comment by NomeQ** [comment]
Debugging steps:
- Set LogLevel: verbose in Document Properties
- Debug Log: Exception: The data you entered in cell S19 violates the data validation rules set on this cell.
- Dropdown validation for "Service ID" had an invalid/incorrect Ref
- Fixed!

**Comment by NomeQ** [comment]
This leaves a few steps in order to improve this process:

- [ ] Document debugging steps in the README, and note common errors (such as incorrectly configured validation rules)
- [ ] Think about whether there is a better UX for showing errors when moving data (other than just the vague toast)
- [ ] Is there a way already within the "fix validation" and "repair sheets" functions to handle this? Check if that would have solved the issue.
- [ ] Consider changing the behavior if there is an error with validation - e.g. do we just ignore and continue? Do we flag the row or something? What else can be done!

**Comment by NomeQ** [comment]
- Kevin's fork includes fix: cell validation is no longer an error, just a warning.
